name: test-build-deploy

on:
  push:
    branch: "vaishnavi"
  pull_request:
    branch: "vaishnavi"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 18
      - name: Test
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 18
      - name: Build
        run: ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-1.0
          path: build/libs/esop-0.1-all.jar

  deploy:
    needs: "build"
    runs-on: ubuntu-latest
    steps:
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-1.0
      - name: Copy jar file to ec2 instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
            eval `ssh-agent`
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
            scp -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$SSH_HOST:~
      - name: Run
        run: sudo java -jar esop-0.1-all.jar





