name: test-build-deploy

on:
  push:
    branch: "vaishnavi"
  pull_request:
    branch: "vaishnavi"
  workflow_call:
    secrets:
      EC2_SSH_KEY:
        required: true
    inputs:
      public_ip:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: vaishnavi
      - name: print input
        run: |
          echo ${{ inputs.public_ip }}
          echo ${{ inputs.public_ip!='' }}

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Test
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: vaishnavi
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-1.0
          path: build/libs/esop-0.1-all.jar

  instance_ip:
    if: ${{ inputs.public_ip!='' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: vaishnavi
      - name: Check for input
        env:
          SSH_HOST: ${{ inputs.public_ip }}
        run: |
              touch public_ip.txt
              echo $SSH_HOST >> public_ip.txt
      - name: Upload public ip file
        uses: actions/upload-artifact@v3
        with:
          name: public_ip
          path: public_ip.txt
        

  deploy:
    needs: ["build","instance_ip"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: vaishnavi
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-1.0
      - name: Download public_ip from artifacts
        uses: actions/download-artifact@v3
        with:
          name: public_ip
      - name: Cat file
        run: cat public_ip.txt
      - name: Copy jar on ec2 instance and run
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          eval `ssh-agent`
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh_host=$(cat public_ip.txt | tr -d '"');
          scp -o StrictHostKeyChecking=no "esop-0.1-all.jar" ec2-user@$ssh_host:~
          ssh -o StrictHostKeyChecking=no ec2-user@$ssh_host -t 'sudo yum install java-17-amazon-corretto-headless -y;
          echo "installed java";
          ssh-keyscan $ssh_host >> ~/.ssh/known_hosts;
          echo "host added";
          pid=$(sudo fuser -v -n tcp 8080);
          echo "$pid";
          #!/bin/sh;
          echo "script";
          if [ $pid ]
            then
            echo "then"
            sudo fuser -k -n tcp 8080  
            echo "process killed"
          fi
          echo "ifend";
          sudo nohup java -jar esop-0.1-all.jar >/dev/null;
          
          

      
          




