name: infra-creation

on:
  push:
    branch: "terraform"
  pull_request:
    branch: "terraform"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Terraform init
        run: cd terraform/aws_instance; terraform init

      - name: Terraform plan
        run: cd terraform/aws_instance; terraform plan


          
          

      
          




