name: test-build-deploy

on:
  push:
    branch: "terraform"
  pull_request:
    branch: "terraform"

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.terraform_output.outputs.public_ip }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Create aws_instance
        id: create_instance
        run: cd terraform/aws_instance; terraform init

      - name: Terraform Apply
        id: terraform_apply
        run: cd terraform/aws_instance; terraform apply -auto-approve -input=false

      - name: Terraform Output
        id: terraform_output
        run: |
          cd terraform/aws_instance
          touch public_ip.txt
          echo public_ip=$(terraform output instance_public_ip) >> public_ip.txt

      - name: Copy ip address to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public_ip
          path: terraform/aws_instance/public_ip.txt



  cicd:
    needs: "terraform"
    uses: VaishnaviM411/esop-trading/.github/workflows/cicd.yml@vaishnavi
    secrets:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

          
          

      
          




